version: '3.8'

services:
  react-app:
    build:
      context: .  # Directory where the Dockerfile and build folder exist
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: react-container
    restart: unless-stopped

